//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledExamStudent
    {
        public int ScheduledExamStudentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ScheduledExamID { get; set; }
    
        public virtual User User { get; set; }
        public virtual ScheduledExam ScheduledExam { get; set; }
    }
}
