//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledExam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduledExam()
        {
            this.ScheduledExamProcters = new HashSet<ScheduledExamProcter>();
            this.ScheduledExamStudents = new HashSet<ScheduledExamStudent>();
        }
    
        public int ScheduledExamID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public string Name { get; set; }
        public Nullable<int> CampusID { get; set; }
        public Nullable<int> ExamStageID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
    
        public virtual Campus Campu { get; set; }
        public virtual Course Course { get; set; }
        public virtual ExamStage ExamStage { get; set; }
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduledExamProcter> ScheduledExamProcters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduledExamStudent> ScheduledExamStudents { get; set; }
    }
}
